### ISSUE TITLE
process gets stuck HHC90020W 'hthread_setschedparam()' failed at loc=cpu.c:2323: rc=22: Invalid argument  

### ISSUE THREAD

**Issue by moshix** [MVS-sysgen/sysgen#1]
I got all the dependencies installed and I can't get the sysgen process to run thru:

<img width="863" alt="Screen Shot 2021-06-06 at 7 38 41 AM" src="https://user-images.githubusercontent.com/18267370/120924698-81361300-c69a-11eb-8c66-b18608d53aa8.png">

**Comment by wrljet** [comment]
The `hthread_setschedparam()` message is not in itself a problem.
That just indicates that the Hercules binaries don't have setcap permission to run at a higher priority.

The real issue is the unknown command, which looks like Rexx isn't installed correctly.

Can you post the hercules.log.

**Comment by wrljet** [comment]
Also, please run this command and post the output:

```ldd `which regina` ```

**Comment by moshix** [comment]
I agree the thread message is not a problem. However, regina seems installed fine:

	linux-vdso.so.1 (0x00007ffc173ac000)
	libregina.so.3 => /lib/libregina.so.3 (0x00007fef76dfa000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fef76c08000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fef76be5000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fef76bdf000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fef77319000)

thanks

M

**Comment by wrljet** [comment]
Please post the hercules.log that was left behind.
Or, run hercules with no arguments, and post the output.

Bill

**Comment by moshix** [comment]
There is no hercules.log in the sysgen/ directory. 

moshix@optiplex9020:~/sysgen$ find . -name hercules.log
moshix@optiplex9020:~/sysgen$

**Comment by MVS-sysgen** [comment]
How did you run the install? 
What OS version?
Can you run `regina -v`?

If it doesn't work you can use any of the build in the releases. Though you'll likely have to manually IPL with the commands in `sysgen/automate.txt`

**Comment by moshix** [comment]
I ran the install with the exact apt install you outlined, then I cloned this repo. 

My OS: Linux optiplex9020 5.8.0-43-generic #49~20.04.1-Ubuntu SMP Fri Feb 5 09:57:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

regina -v
REXX-Regina_3.6(MT) 5.00 31 Dec 2011

**Comment by MVS-sysgen** [comment]
what happens if you run it with `./sysgen.sh --skip-hercules` does it still wait forever?

**Comment by moshix** [comment]
I did run it with with skip-hercules and the exact above error happens.

**Comment by MVS-sysgen** [comment]
Can you run `bash 02_sysgen_build_starter.sh` and then paste the contents of hercules.log here after quitting hercules? Give it about 5 minutes before quitting.

**Comment by moshix** [comment]
I think that's the problem:

exec ../automate.rexx ../01_sysgen_starter.txt hercules.log -d &&
ipl 280

It can't find automate.rexx because it is looking for it outside of the sysgen directory. why does it go to ../ ?

From what directory am I supposed to launch sysgen.sh ?

**Comment by MVS-sysgen** [comment]
sysgen should be launched from the root folder of this repo. 

Hold on, i just noticed it says `Unknown command exec` did you compile hercules with rexx integration (i.e. it completed the first step compiling hercules)?

**Comment by MVS-sysgen** [comment]
Can you run `/usr/local/bin/hercules > log.txt` and upload `log.txt` here. 

I'm specifically looking for `02:45:16 HHC01417I With    Regina REXX support` and:

```02:45:16 HHC17528I REXX(Regina) VERSION: REXX-Regina_3.6(MT) 5.00 31 Dec 2011
02:45:16 HHC17529I REXX(Regina) SOURCE:  UNIX
02:45:16 HHC17525I REXX(Regina) Rexx has been started/enabled
02:45:16 HHC17500I REXX(Regina) Mode            : Command
02:45:16 HHC17500I REXX(Regina) MsgLevel        : Off
02:45:16 HHC17500I REXX(Regina) MsgPrefix       : Off
02:45:16 HHC17500I REXX(Regina) ErrPrefix       : Off
02:45:16 HHC17500I REXX(Regina) Resolver        : On
02:45:16 HHC17500I REXX(Regina) SysPath    ( 9) : On
02:45:16 HHC17500I REXX(Regina) RexxPath   ( 0) :
02:45:16 HHC17500I REXX(Regina) Extensions ( 8) : .REXX:.rexx:.REX:.rex:.CMD:.cmd:.RX:.rx
```

**Comment by moshix** [comment]
You were right. I didn't have rexx compiled into hyperion. Now, I do, however, now when I start sysgen.sh it gets stuck at this spot and the instruction counter stays put:

HHC00007I Previous message from function 'hthread_set_thread_prio' at hthreads.c(11+
HHC90020W 'hthread_setschedparam()' failed at loc=timer.c:193: rc=22: Invalid argume
HHC00007I Previous message from function 'hthread_set_thread_prio' at hthreads.c(117
HHC00100I Thread id 00007fbf9e4f5700, prio 0, name 'Processor CP00' started         
HHC00100I Thread id 00007fbf9e3f4700, prio 0, name 'timer_thread' started           
HHC00811I Processor CP00: architecture mode z/Arch                                  
HHC00811I Processor CP00: architecture mode S/370                                   
HHC02204I ARCHLVL        set to S/370                                               
HHC02204I LPARNUM        set to BASIC                                               
HHC02204I CPUSERIAL      set to 000611                                              
HHC02204I CPUMODEL       set to 0148                                                
HHC17003I MAIN     storage is 8M (mainsize); storage is not locked                  
HHC17003I EXPANDED storage is 0 (xpndsize); storage is not locked                   
HHC02204I NUMCPU         set to 1                                                   
HHC02204I LOADPARM       set to ........                                            
HHC00414I 0:0150 CKD file dasd/start1.3330: model 3330 cyls 411 heads 19 tracks 7809
HHC00414I 0:0151 CKD file dasd/spool0.3330: model 3330 cyls 411 heads 19 tracks 7809
HHC00221I 0:0280 Tape file tape/vs2start.het, type HET: format type Hercules Emulate
HHC00221I 0:0281 Tape file tape/vs2spool.het, type HET: format type Hercules Emulate
HHC02260I Script 1: begin processing file ../01_sysgen_starter.rc                   
HHC01603I * IPLing the Starter System                                               
HHC01603I ostailor default                                                          
HHC01603I panopt msgcolor=dark                                                      
HHC02204I PANOPT         set to FULLPATH RATE=500 MSGCOLOR=DARK TITLE=(default)     
HHC01603I shcmdopt enable                                                           
HHC02204I SHCMDOPT       set to ENABLE  NODIAG8                                     
HHC01603I pantitle "Build System Starter"                                           
HHC02256W Command 'PANTITLE' is deprecated; use PANOPT TITLE=xxx instead            
HHC00007I Previous message from function 'pantitle_cmd' at hsccmd.c(4205)           
HHC02204I PANTITLE       set to Build System Starter                                
HHC01603I exec ../automate.rexx ../01_sysgen_starter.txt hercules.log -d &&         
HHC01600E Unknown command exec, enter 'help' for a list of valid commands           
HHC00007I Previous message from function 'DoCallHercCmdLine' at cmdtab.c(430)       
HHC01603I ipl 280                                                                   
HHC02264I Script 1: file ../01_sysgen_starter.rc processing ended                   
herc =====>

**Comment by moshix** [comment]
I let it build Hercules and now it's running.

**Comment by MVS-sysgen** [comment]
According to the log you sent the version its running still doesn't have rexx:

> HHC01603I exec ../automate.rexx ../01_sysgen_starter.txt hercules.log -d &&
HHC01600E Unknown command exec, enter 'help' for a list of valid commands
HHC00007I Previous message from function 'DoCallHercCmdLine' at cmdtab.c(430)

The script checks to see if you have hercules installed at `/usr/local/bin/hercules` and if not just uses hercules from your path (this is line 83 of `00_sysgen_functions.sh`

**Comment by MVS-sysgen** [comment]
If (more likely when) you run in to another problem building feel free to open another ticket, i'm going to close this one for now. 

I'll probably add a config parameter to get rid of the `htthread` messages
