### ISSUE TITLE
 error while loading shared libraries: libherc.so

### ISSUE THREAD

**Issue by moshix** [MVS-sysgen/sysgen#14]
On ubuntu 20.04 got his error. Looks familiar but dont' remember right now how to resolve it. Any ideas?

thanks

M

This script creates DASD volumes for MVS 3.8j.
Creating dasd subdirectory
Changed directory to: /home/moshe/sysgen/sysgen/dasd
dasdinit -a -z start1.3330 3330 111111
dasdinit: error while loading shared libraries: libhercu.so: cannot open shared object file: No such file or directory
dasdinit -a -z spool0.3330 3330 222222
dasdinit: error while loading shared libraries: libhercu.so: cannot open shared object file: No such file or directory
Returning to parent directory
Script completed successfully!
[+] Starting Hercules: hercules -f conf/ibcdmprs.cnf -r ../01_sysgen_starter.rc -d
[+] Log file: sysgen.build_starter.2021-08-10-085805.log
/usr/local/bin/hercules: error while loading shared libraries: libherc.so: cannot open shared object file: No such file or directory

        ***************
        *** ABORTED ***
        ***************
        
[!] Error encoutered exiting.

        ***************
        *** ABORTED ***
        ***************
        
[!] Error encoutered exiting.

**Comment by mgrossmann** [comment]
Hi Moshe,

please do a`sudo ldconfig`after hercules build step.
Then restart sysgen with `--skip-hercules`

/Mike

**Comment by moshix** [comment]
seems to work. thanks Mike!

M
