### ISSUE TITLE
DLBUCL RC 0008

### ISSUE THREAD

**Issue by moshix** [MVS-sysgen/sysgen#15]
Installing telnet32.Debug ...

[100%] Built target telnet32d
Install the project...
-- Install configuration: "Debug"
-- Installing: /root/sysgen/build/hercpkgs/lib/libtelnet32d.a
-- Installing: /root/sysgen/build/hercpkgs/include/telnet.h
-- Installing: /root/sysgen/build/hercpkgs/include/telnet_version.h
-- Installing: /root/sysgen/build/hercpkgs/./telnet.LICENSE.txt
-- Installing: /root/sysgen/build/hercpkgs/./telnet.README.txt

Build SUCCEEDED on Tue 08/10/21 at 08:49:08

cmdline = build --pkgname . --all --install ../../hercpkgs

Build of 32-bit Release version of telnet begun on Tue 08/10/21 at 08:49:08

Configuring telnet32.Release ...

-- The C compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
++ SOURCE_DIR '/root/sysgen/build/telnet' 
++ BINARY_DIR '/root/sysgen/build/WORK/telnet/telnet32.Release' 
++ BINARY_DIR_NAME 'telnet32.Release' 
++ TRUNCATED_BINARY_DIR '/root/sysgen/build/WORK/telnet' 
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
++ BINARY_HLQ '/root/sysgen/build/WORK/telnet' 
++ BINARY_DIR 'telnet32.Release' 
++ _xxxxx 'telnet32' 
++ CONFIG 'Release' 
++ CMAKE_BUILD_TYPE 'RelWithDebInfo' 
++ BASENAME 'telnet' 
++ BITNESS '32' 
++ CONFIG 'Release' 
++ DBGCHAR '' 
++ SUFFIX '32' 
++ FULLNAME 'telnet32' 
++ CMAKE_BINARY_DIR '/root/sysgen/build/WORK/telnet/telnet32.Release' 
++ CMAKE_INSTALL_PREFIX '/root/sysgen/build/hercpkgs' 
++ LIB_INSTALL_DIR 'lib' 
-- Found Git: /usr/bin/git (found version "2.25.1") 
++ GIT_COMMIT_COUNT '59' 
++ GIT_HASH7 '2aca101' 
++ GIT_MODIFIED '' 
Building telnet32 version 1.0.0.59-g2aca101
-- Looking for stdbool.h
-- Looking for stdbool.h - found
-- Performing Test OK
-- Performing Test OK - Failed
++ CMAKE_C_FLAGS_DEBUG '-g                    -D HAVE_PLATFORM_H -D DEBUG          -D VERS_STRING=1.0.0.59-g2aca101           -fPIC' 
++ CMAKE_C_FLAGS_RELWITHDEBINFO '-O2 -g -DNDEBUG  -D HAVE_PLATFORM_H -D VERS_STRING=1.0.0.59-g2aca101  -fPIC' 
-- Configuring done
-- Generating done
-- Build files have been written to: /root/sysgen/build/WORK/telnet/telnet32.Release

Building telnet32.Release ...

Scanning dependencies of target telnet32
[ 66%] Building C object CMakeFiles/telnet32.dir/telnet_version.c.o
[ 66%] Building C object CMakeFiles/telnet32.dir/source/telnet.c.o
[100%] Linking C static library libtelnet32.a
[100%] Built target telnet32

Installing telnet32.Release ...

[100%] Built target telnet32
Install the project...
-- Install configuration: "RelWithDebInfo"
-- Installing: /root/sysgen/build/hercpkgs/lib/libtelnet32.a
-- Up-to-date: /root/sysgen/build/hercpkgs/include/telnet.h
-- Up-to-date: /root/sysgen/build/hercpkgs/include/telnet_version.h
-- Up-to-date: /root/sysgen/build/hercpkgs/./telnet.LICENSE.txt
-- Up-to-date: /root/sysgen/build/hercpkgs/./telnet.README.txt

Build SUCCEEDED on Tue 08/10/21 at 08:49:10

cmdline = build --pkgname . --all --install ../../hercpkgs

Build of 64-bit Debug version of telnet begun on Tue 08/10/21 at 08:49:10

Configuring telnet64.Debug ...

-- The C compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
++ SOURCE_DIR '/root/sysgen/build/telnet' 
++ BINARY_DIR '/root/sysgen/build/WORK/telnet/telnet64.Debug' 
++ BINARY_DIR_NAME 'telnet64.Debug' 
++ TRUNCATED_BINARY_DIR '/root/sysgen/build/WORK/telnet' 
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
++ BINARY_HLQ '/root/sysgen/build/WORK/telnet' 
++ BINARY_DIR 'telnet64.Debug' 
++ _xxxxx 'telnet64' 
++ CONFIG 'Debug' 
++ CMAKE_BUILD_TYPE 'Debug' 
++ BASENAME 'telnet' 
++ BITNESS '64' 
++ CONFIG 'Debug' 
++ DBGCHAR 'd' 
++ SUFFIX '64d' 
++ FULLNAME 'telnet64d' 
++ CMAKE_BINARY_DIR '/root/sysgen/build/WORK/telnet/telnet64.Debug' 
++ CMAKE_INSTALL_PREFIX '/root/sysgen/build/hercpkgs' 
++ LIB_INSTALL_DIR 'lib' 
-- Found Git: /usr/bin/git (found version "2.25.1") 
++ GIT_COMMIT_COUNT '59' 
++ GIT_HASH7 '2aca101' 
++ GIT_MODIFIED '' 
Building telnet64d version 1.0.0.59-g2aca101
-- Looking for stdbool.h
-- Looking for stdbool.h - found
-- Performing Test OK
-- Performing Test OK - Failed
++ CMAKE_C_FLAGS_DEBUG '-g                    -D HAVE_PLATFORM_H -D DEBUG          -D VERS_STRING=1.0.0.59-g2aca101           -fPIC' 
++ CMAKE_C_FLAGS_RELWITHDEBINFO '-O2 -g -DNDEBUG  -D HAVE_PLATFORM_H -D VERS_STRING=1.0.0.59-g2aca101  -fPIC' 
-- Configuring done
-- Generating done
-- Build files have been written to: /root/sysgen/build/WORK/telnet/telnet64.Debug

Building telnet64.Debug ...

Scanning dependencies of target telnet64d
[ 66%] Building C object CMakeFiles/telnet64d.dir/telnet_version.c.o
[ 66%] Building C object CMakeFiles/telnet64d.dir/source/telnet.c.o
[100%] Linking C static library libtelnet64d.a
[100%] Built target telnet64d

Installing telnet64.Debug ...

[100%] Built target telnet64d
Install the project...
-- Install configuration: "Debug"
-- Installing: /root/sysgen/build/hercpkgs/lib/libtelnet64d.a
-- Up-to-date: /root/sysgen/build/hercpkgs/include/telnet.h
-- Up-to-date: /root/sysgen/build/hercpkgs/include/telnet_version.h
-- Up-to-date: /root/sysgen/build/hercpkgs/./telnet.LICENSE.txt
-- Up-to-date: /root/sysgen/build/hercpkgs/./telnet.README.txt

Build SUCCEEDED on Tue 08/10/21 at 08:49:11

cmdline = build --pkgname . --all --install ../../hercpkgs

Build of 64-bit Release version of telnet begun on Tue 08/10/21 at 08:49:11

Configuring telnet64.Release ...

-- The C compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
++ SOURCE_DIR '/root/sysgen/build/telnet' 
++ BINARY_DIR '/root/sysgen/build/WORK/telnet/telnet64.Release' 
++ BINARY_DIR_NAME 'telnet64.Release' 
++ TRUNCATED_BINARY_DIR '/root/sysgen/build/WORK/telnet' 
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
++ BINARY_HLQ '/root/sysgen/build/WORK/telnet' 
++ BINARY_DIR 'telnet64.Release' 
++ _xxxxx 'telnet64' 
++ CONFIG 'Release' 
++ CMAKE_BUILD_TYPE 'RelWithDebInfo' 
++ BASENAME 'telnet' 
++ BITNESS '64' 
++ CONFIG 'Release' 
++ DBGCHAR '' 
++ SUFFIX '64' 
++ FULLNAME 'telnet64' 
++ CMAKE_BINARY_DIR '/root/sysgen/build/WORK/telnet/telnet64.Release' 
++ CMAKE_INSTALL_PREFIX '/root/sysgen/build/hercpkgs' 
++ LIB_INSTALL_DIR 'lib' 
-- Found Git: /usr/bin/git (found version "2.25.1") 
++ GIT_COMMIT_COUNT '59' 
++ GIT_HASH7 '2aca101' 
++ GIT_MODIFIED '' 
Building telnet64 version 1.0.0.59-g2aca101
-- Looking for stdbool.h
-- Looking for stdbool.h - found
-- Performing Test OK
-- Performing Test OK - Failed
++ CMAKE_C_FLAGS_DEBUG '-g                    -D HAVE_PLATFORM_H -D DEBUG          -D VERS_STRING=1.0.0.59-g2aca101           -fPIC' 
++ CMAKE_C_FLAGS_RELWITHDEBINFO '-O2 -g -DNDEBUG  -D HAVE_PLATFORM_H -D VERS_STRING=1.0.0.59-g2aca101  -fPIC' 
-- Configuring done
-- Generating done
-- Build files have been written to: /root/sysgen/build/WORK/telnet/telnet64.Release

Building telnet64.Release ...

Scanning dependencies of target telnet64
[ 66%] Building C object CMakeFiles/telnet64.dir/telnet_version.c.o
[ 66%] Building C object CMakeFiles/telnet64.dir/source/telnet.c.o
[100%] Linking C static library libtelnet64.a
[100%] Built target telnet64

Installing telnet64.Release ...

[100%] Built target telnet64
Install the project...
-- Install configuration: "RelWithDebInfo"
-- Installing: /root/sysgen/build/hercpkgs/lib/libtelnet64.a
-- Up-to-date: /root/sysgen/build/hercpkgs/include/telnet.h
-- Up-to-date: /root/sysgen/build/hercpkgs/include/telnet_version.h
-- Up-to-date: /root/sysgen/build/hercpkgs/./telnet.LICENSE.txt
-- Up-to-date: /root/sysgen/build/hercpkgs/./telnet.README.txt

Build SUCCEEDED on Tue 08/10/21 at 08:49:13

[+] Building Hercules Hyperion SDL
Cloning into 'hyperion'...
remote: Enumerating objects: 55096, done.
remote: Counting objects: 100% (736/736), done.
remote: Compressing objects: 100% (429/429), done.
^Cceiving objects:  31% (17080/55096), 18.77 MiB | 18.76 MiB/s
        ***************
        *** ABORTED ***
        ***************
        
[!] Error encoutered exiting.

        ***************
        *** ABORTED ***
        ***************
        
[!] Error encoutered exiting.

root@system:~/sysgen# su - moshe
moshe@system:~$ git clone ./sysgen.sh
fatal: repository './sysgen.sh' does not exist
moshe@system:~$ git clone https://github.com/MVS-sysgen/sysgen.git
Cloning into 'sysgen'...
remote: Enumerating objects: 1144, done.
remote: Counting objects: 100% (784/784), done.
remote: Compressing objects: 100% (576/576), done.
remote: Total 1144 (delta 344), reused 609 (delta 203), pack-reused 360
Receiving objects: 100% (1144/1144), 133.95 MiB | 36.63 MiB/s, done.
Resolving deltas: 100% (498/498), done.
moshe@system:~$ cd sysgen/
moshe@system:~/sysgen$ ls
00_sysgen_functions.sh                     05_sysgen_customization.sh
01_install_smp4.txt                        05_sysgen_system_customization.rc
01_sysgen_build_hercules.sh                06_sysgen_software_install.rc
01_sysgen_starter.rc                       06_sysgen_software_install.sh
01_sysgen_starter.txt                      06_sysgen_software_install.txt
02_install_dist_libs.txt                   README.md
02_sysgen_build_dist.rc                    SOFTWARE
02_sysgen_build_starter.sh                 automate.md
03_sysgen_build_dist_2.rc                  automate.rexx
03_sysgen_build_distribution_libraries.sh  documentation
03_system_generation.txt                   gz
04_sysgen_system_generation.rc             make_release.sh
04_sysgen_system_generation.sh             sysgen
04_system_customization.txt                sysgen.sh
moshe@system:~/sysgen$ ./sysgen.sh 
[+] Building SDL Hercules from source
[+] Building external packages
[+] Building crypto
Cloning into 'crypto'...
remote: Enumerating objects: 285, done.
remote: Counting objects: 100% (76/76), done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 285 (delta 39), reused 48 (delta 20), pack-reused 209
Receiving objects: 100% (285/285), 215.51 KiB | 2.80 MiB/s, done.
Resolving deltas: 100% (162/162), done.
cmdline = build --pkgname . --all --install ../../hercpkgs

Build of 32-bit Debug version of crypto begun on Tue 08/10/21 at 08:49:51

Configuring crypto32.Debug ...

-- The C compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
++ SOURCE_DIR '/home/moshe/sysgen/build/crypto' 
++ BINARY_DIR '/home/moshe/sysgen/build/WORK/crypto/crypto32.Debug' 
++ BINARY_DIR_NAME 'crypto32.Debug' 
++ TRUNCATED_BINARY_DIR '/home/moshe/sysgen/build/WORK/crypto' 
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
++ BINARY_HLQ '/home/moshe/sysgen/build/WORK/crypto' 
++ BINARY_DIR 'crypto32.Debug' 
++ _xxxxx 'crypto32' 
++ CONFIG 'Debug' 
++ CMAKE_BUILD_TYPE 'Debug' 
++ BASENAME 'crypto' 
++ BITNESS '32' 
++ CONFIG 'Debug' 
++ DBGCHAR 'd' 
++ SUFFIX '32d' 
++ FULLNAME 'crypto32d' 
++ CMAKE_BINARY_DIR '/home/moshe/sysgen/build/WORK/crypto/crypto32.Debug' 
++ CMAKE_INSTALL_PREFIX '/home/moshe/sysgen/build/hercpkgs' 
++ LIB_INSTALL_DIR 'lib' 
-- Found Git: /usr/bin/git (found version "2.25.1") 
++ GIT_COMMIT_COUNT '49' 
++ GIT_HASH7 '837705e' 
++ GIT_MODIFIED '' 
Building crypto32d version 1.0.0.49-g837705e
-- Looking for stdbool.h
-- Looking for stdbool.h - found
-- Performing Test OK
-- Performing Test OK - Failed
++ CMAKE_C_FLAGS_DEBUG '-g           -D LITTLE_ENDIAN=1234 -D BIG_ENDIAN=4321 -D BYTE_ORDER=LITTLE_ENDIAN          -D HAVE_PLATFORM_H -D DEBUG          -D VERS_STRING=1.0.0.49-g837705e           -fPIC' 
++ CMAKE_C_FLAGS_RELWITHDEBINFO '-O2 -g -DNDEBUG  -D LITTLE_ENDIAN=1234 -D BIG_ENDIAN=4321 -D BYTE_ORDER=LITTLE_ENDIAN -D HAVE_PLATFORM_H -D VERS_STRING=1.0.0.49-g837705e  -fPIC' 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/moshe/sysgen/build/WORK/crypto/crypto32.Debug

Building crypto32.Debug ...

Scanning dependencies of target crypto32d
[ 33%] Building C object CMakeFiles/crypto32d.dir/source/rijndael.c.o
[ 33%] Building C object CMakeFiles/crypto32d.dir/crypto_version.c.o
[ 50%] Building C object CMakeFiles/crypto32d.dir/source/sha1.c.o
[ 66%] Building C object CMakeFiles/crypto32d.dir/source/sha2.c.o
[ 83%] Building C object CMakeFiles/crypto32d.dir/source/sshdes.c.o
[100%] Linking C static library libcrypto32d.a
[100%] Built target crypto32d

Installing crypto32.Debug ...

[100%] Built target crypto32d
Install the project...
-- Install configuration: "Debug"
-- Installing: /home/moshe/sysgen/build/hercpkgs/lib/libcrypto32d.a
-- Installing: /home/moshe/sysgen/build/hercpkgs/include/crypto_version.h
-- Installing: /home/moshe/sysgen/build/hercpkgs/include/crypto.h
-- Installing: /home/moshe/sysgen/build/hercpkgs/include/rijndael.h
-- Installing: /home/moshe/sysgen/build/hercpkgs/include/sha1.h
-- Installing: /home/moshe/sysgen/build/hercpkgs/include/sha2.h
-- Installing: /home/moshe/sysgen/build/hercpkgs/include/sshdes.h
-- Installing: /home/moshe/sysgen/build/hercpkgs/./crypto.LICENSE.txt
-- Installing: /home/moshe/sysgen/build/hercpkgs/./crypto.README.txt

Build SUCCEEDED on Tue 08/10/21 at 08:49:53

cmdline = build --pkgname . --all --install ../../hercpkgs

Build of 32-bit Release version of crypto begun on Tue 08/10/21 at 08:49:53

Configuring crypto32.Release ...

-- The C compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
^C
        ***************
        *** ABORTED ***
        ***************
        
[!] Error encoutered exiting.

        ***************
        *** ABORTED ***
        ***************
        
[!] Error encoutered exiting.

moshe@system:~/sysgen$ screen -S sysgen

Job Name    Step Name    Proc Step Name    Completion Code
--------    ---------    --------------    ---------------
MOUNT       148                            0000
 
  1 steps executed in selected jobs
  1 steps received completion code = 0000
Searching prt00e.txt for MVS Job Name smpjob00
 
Job Name    Step Name    Proc Step Name    Completion Code
--------    ---------    --------------    ---------------
SMPJOB00    IEHPROGM                       0008 <--
SMPJOB00    IEFBR14                        0000
SMPJOB00    SMP          DLBUCL            0008 <--
 
  3 steps executed in selected jobs
  1 steps received completion code = 0000
  2 steps received completion code = 0008
Searching prt00e.txt for MVS Job Name smpjob01
 
Job Name    Step Name    Proc Step Name    Completion Code
--------    ---------    --------------    ---------------
SMPJOB01    SMP          DLBUCL            0008 <--
 
  1 steps executed in selected jobs
  1 steps received completion code = 0008

        ***************
        *** ABORTED ***
        ***************
        
[!] Error encoutered exiting.

        ***************
        *** ABORTED ***
        ***************
        
[!] Error encoutered exiting.

**Comment by mgrossmann** [comment]
Hey Moshe,

why is there a `^C`?


/Mike

**Comment by moshix** [comment]
Yes, it went away on its own. 

thx

M

**Comment by wrljet** [comment]
Closed, but it'll be back. :-)
