### ISSUE TITLE
Feature request: NJE38, IM monitor

### ISSUE THREAD

**Issue by moshix** [MVS-sysgen/sysgen#2]
Just ran a full SYSGEN. Worked fine. 

I am humbly asking if we could add Bob Polmanter's NJE38, Greg Price's MON. 

like what you have done with this!

thanks

M

**Comment by MVS-sysgen** [comment]
IMON370 has been added, if you do a `git pull` in the sysgen repo you should be able to type `INSTALL IMON370` in TSO to install it.
