### ISSUE TITLE
Outdated usermods ZP60039 and ZP60040

### ISSUE THREAD

**Issue by rfc1459** [MVS-sysgen/sysgen#25]
The version of [ZP60039][] and [ZP60040][] shipped with MVSCE can cause spurious SD23 abends of the R console command if the WTO/WTOR message is too long. The abend (and subsequent dump) can be reliably triggered by replying to the WTOR used by INTERCOMM to handle operator commands.

Both usermods have been updated in August 2020 to fix that issue.

[ZP60039]: http://www.prycroft6.com.au/vs2mods/zp60039.txt
[ZP60040]: http://www.prycroft6.com.au/vs2mods/zp60040.txt

**Comment by mainframed** [comment]
Can i get a link to the newer usermods?

**Comment by rfc1459** [comment]
Sure, they're at the usual place: http://www.prycroft6.com.au/vs2mods/download/zp60039.zip
