### ISSUE TITLE
Any possibility of an arm64 Docker image?

### ISSUE THREAD

**Issue by lnlyssg** [MVS-sysgen/sysgen#29]
As per the title, I would like to run this on my M2 MacBook Air but that needs an arm64 version of the Docker image.

**Comment by mainframed** [comment]
So for this to work you'd need to build a hercules-arm64 docker container, then you should be able to run this without any problems on top of that.

**Comment by mainframed** [comment]
Finally have an ARM system I can build this on, i'll get to it.

**Comment by mainframed** [comment]
Finally got around to this over the weekend. You should be able to do a docker run on both arm and amd architectures now.
