### ISSUE TITLE
RC0008 and above during my SYSGEN

### ISSUE THREAD

**Issue by moshix** [MVS-sysgen/sysgen#3]
SMPJOB00    IEHPROGM                       0008 <--
SMPJOB00    SMP          DLBUCL            0008 <--
RAKFPREP    DELETE                         0008 <--
RAKFCUST    SCRATCH                        0008 <--
RFESC1F4    STEP1                          0008 <--
SYSGEN00    IEHPROGM                       0008 <--
SYSGEN01    CLEANUP                        0008 <--
SYSGEN6     STEPZ1                         0008 <--

RAKFPTF2    HMASMP       RRKF001           0012 <--
RAKFPTF2    HMASMP       RRKF002           0012 <--
RAKFPTF2    HMASMP       RRKF003           0012 <--
RAKFPTF2    HMASMP       RRKF004           0012 <--
RAKFPTF2    HMASMP       RRKF005           0012 <--
RAKFPTF2    HMASMP       RRKF006           0012 <--
RAKFCUST    HMASMP       RECEIVE           0012 <--

**Comment by MVS-sysgen** [comment]
- SMPJOB00, SYSGEN00, SYSGEN01, and SYSGEN6 - These are expected

**Comment by MVS-sysgen** [comment]
- RAKFPTF2 and RAKFCUST are expected
- RFESC1F4 - this was no longer needed and will be removed
