### ISSUE TITLE
script sysgen.py doesn't find what it's looking for

### ISSUE THREAD

**Issue by HarmBacker** [MVS-sysgen/sysgen#30]
In the script sysgen.py, there are some lines where the string it's waiting for seems not to be correct.
Expression in the script: self.wait_for_string("0:xxx CKD")
where is should better be: self.wait_for_string("0:xxx CCKD")
Some of these are commented but there are some active ones where it's waiting forever.
I changed a version and that one is working fine.

**Comment by mainframed** [comment]
Turns out this was an issue with Hercules 4.5 and greater. I've fixed this and just pushed out a new release.
