### ISSUE TITLE
In ISPF panel ISPREVE the panel fields are revb... instead of reve... looks like regression since they are ok on backup member

### ISSUE THREAD

**Issue by dliloch** [MVS-sysgen/sysgen#31]
on MVSCE v2.0.0;
I tried to edit a dataset from main panel using edit (panelid is ISPREVE) and got the following error error ..
IF VARIABLE NOT FOUND  
PF1 gives
SP271E - LINE # 001 IF VARIABLE REVEDSN NOT FOUND       
looking at the panel I saw this ... so just changed all the revb  to reve and it worked fine.

ISPF Library:                                                       
                                                                    
   Project  . ._revbproj+                       << changed to reveproj                     
   Group  . . ._revbgrp +                                           
   Type . . . ._revbtype+                                           
   Member . . ._revbmem +       (Blank for member selection list)   
                                                                    
                                                                    
Other partitioned or sequential dataset:                            
                                                                    
   Name  . . . . . . ._revbdsn                                     +
   Volume Serial . . ._z     +   (If not cataloged)                 
 maybe mixed up with the browse panel ISPREVB panel?

**Comment by mainframed** [comment]
Thanks for the heads up, i've fixed it here: https://github.com/MVS-sysgen/MVP/commit/e11b071ba49e698df64f8a63a0562777548f67bc
