### ISSUE TITLE
sysgen.py abends because of job SMPJOB03, step DLBUCL2 returns unexpected return code 0012

### ISSUE THREAD

**Issue by HarmBacker** [MVS-sysgen/sysgen#32]
Hello,

I just started latest sysgen.py to generate a new system but it abends in that step. This happened before the latest release as well.
I attach prt00e.txt as a zip file for your reference here:.
[prt00e.zip](https://github.com/MVS-sysgen/sysgen/files/10951028/prt00e.zip)

When restarting with-C option, DLBUCL2 ends with cc 0004.
SMPJOB04 runs well but after job SMPJOB05 ends, I see following message :
--- snip ---
13:40:22,791 root DEBUG [HERCLOG] / $HASP395 SMPJOB05 ENDED
13:40:22,797 root DEBUG [HERCLOG] / $HASP309    INIT  1 INACTIVE ******** C=A
13:40:22,803 root DEBUG [HERCLOG] / $HASP150 SMPJOB05 ON PRINTER1
13:40:23,29 root DEBUG [HERCLOG] / $HASP095 JES2 SYSTEM CATASTROPHIC ERROR.  CODE = A01
13:40:23,39 root DEBUG Reply number set to 02
13:40:23,44 root DEBUG [HERCLOG] /*02 $HASP098 ENTER TERMINATION OPTION
13:40:23,565 root DEBUG [DIAG] MIPS=   7.21
13:40:24,551 root DEBUG [DIAG] MIPS=   0.01
13:40:25,553 root DEBUG [DIAG] MIPS=   0.00
--- snip ---
After 10 minutes, only MIPS= 0.00 is shown until a timeout (set to 2400 seconds) occurs.
Is it possible that the first issue (RC 0012 in SMPJOB03 step DLBUCL2) causes the second issue?
As I can replicate the issue, I can also deliver the sysgen.log file from the first abend.

Thank you for checking!
Harm

**Comment by mainframed** [comment]
Does this happen every time you rerun this step with the `-C` flag?

What version of hercules?

**Comment by HarmBacker** [comment]
Hello,

thank you for caring!

Hercules version is 4.5.0.10830-SDL-g58578601.

Today I started another sysgen git clone into new sysgen-054 folder (my 54th attempt...).

First start in a terminal session with './sysgen.py' command ended with rc=0012 in job SMPJOB03, step DLBUCL2.
--> see attached files I saved at that point.
[sysgen.log_after start abend.zip](https://github.com/MVS-sysgen/sysgen/files/10960306/sysgen.log_after.start.abend.zip)
[prt00e.txt_after start abend.zip](https://github.com/MVS-sysgen/sysgen/files/10960309/prt00e.txt_after.start.abend.zip)

First restart in same terminal session with './sysgen.py --timeout=4800 -C' ended with same issue.
--> see attached files I saved at that point.
[sysgen.log_after restart abend 1.zip](https://github.com/MVS-sysgen/sysgen/files/10960332/sysgen.log_after.restart.abend.1.zip)
[prt00e.txt_after restart abend 1.zip](https://github.com/MVS-sysgen/sysgen/files/10960333/prt00e.txt_after.restart.abend.1.zip)

Second restart all the same.
--> see attached files I saved at that point.
[sysgen.log_after restart abend 2.zip](https://github.com/MVS-sysgen/sysgen/files/10960342/sysgen.log_after.restart.abend.2.zip)
[prt00e.txt_after restart abend 2.zip](https://github.com/MVS-sysgen/sysgen/files/10960343/prt00e.txt_after.restart.abend.2.zip)

Sometimes, the installation is interrupted already in step DLBUCL (job SMPJOB00), in that case I start ./sysgen.py again without -C .
I can also upload the respective files after that abend as well if you are interested in.

Regards,
Harm

**Comment by HarmBacker** [comment]
Hello Bill,

thank you for your answer.

You wrote the error(s?) occur randomly: does it mean I can restart with -C option again and again until the error doesn't come up again to finally have a working system?

Regards,
Harm

**Comment by wrljet** [comment]
The answer is Yes, but, your experience seems to be having this problem a lot more frequently than what I've seen as normal.

With that in mind, I have a few questions, that may help us with the quest to find this bug:
- What Linux distro are you running?
- Real hardware or a VM?
- How many CPU cores?
- How much RAM?
- Did you build your Hercules yourself?  If so, do you know what options you passed to `configure`?

I would recommend you rebuild Hercules and checkout the `develop` branch of the git repo.

If you need/want any help in that area, please do no hesitate to ask.

Bill

**Comment by HarmBacker** [comment]
Hello Bill,

thank you for your reply.

I'm running Ubuntu 22.10 distro on real hardware (Lenovo laptop model G580) with 4 CPUs and 8 GB RAM

The Hercules I built myself, using the script published in section 'Building and Installing Hercules' on page https://github.com/MVS-sysgen/sysgen without any specific options - just the pure script.

I'll try to rebuild it from the develop git repro.

Regards,
Harm

**Comment by wrljet** [comment]
It is *very* random.  The most popular failing job for me, DLBUCL2, sometimes fails 1 out of maybe 5 runs.
Sometimes will run 100 times without failing.

**Comment by mainframed** [comment]
> 

@HarmBacker whenever I want to build sysgen fully (i.e. I'm not testing some setting change on a step) i use `until ./sysgen.py --timeout 500 --CONTINUE; do echo "Failed, rerunning"; done` (adjust timeout as needed).

**Comment by HarmBacker** [comment]
@mainframed thank you for that piece of coding, it works well for issues coming up from time to time.
My overall understading _was_ that the installation script should run error-free most of the times - except for me... Now I learnt that others have same issues and this is a good workaround so far.
