### ISSUE TITLE
Shutdown failes because files are not in expected folder

### ISSUE THREAD

**Issue by HarmBacker** [MVS-sysgen/sysgen#33]
Hello,

when shutting down Hercules the first time after installation, I got error messages and it won't get down.

Looking into it, I realized that Hercules tries to run scripts pjes2, poweroff, quiesce and zeod from folder scripts (lowercase) - that folder doesn't exist.
There is a folder SCRIPTS (uppercase) where these 4 files are in. I created the SCRIPTS folder and moved the 4 files into it - and it works well now.

Maybe, this can be fixed for next release?

Thank you!
Harm

**Comment by mainframed** [comment]
Great catch. Unfortunately the folder needs to remain uppercase otherwise you cant issue the shutdown commands from BREXX. But I've updated the shutdown script and github is generating a new release now.
