### ISSUE TITLE
HHC90020W 'hthread_setschedparam()' failed at loc=console.c:3409: rc=22: Invalid argument

### ISSUE THREAD

**Issue by gmgauthier** [MVS-sysgen/sysgen#38]
This error pops up fairly frequently:
```
HHC90020W 'hthread_setschedparam()' failed at loc=console.c:3409: rc=22: Invalid argument
HHC00007I Previous message from function 'hthread_set_thread_prio' at hthreads.c(1171)
HHC00100I Thread id 00007f63b4550700, prio 0, name 'console_connect' started
```
and later
```
HHC00107I Starting thread cckd_writer() from cckd_writer(), active=1, started=1, max=2
HHC90020W 'hthread_setschedparam()' failed at loc=cckddasd.c:1793: rc=22: Invalid argument
HHC00007I Previous message from function 'hthread_set_thread_prio' at hthreads.c(1171)
HHC00100I Thread id 00007f6387bfb700, prio 0, name 'cckd_writer thread 2' started
```
I see it popping up in other contexts online, as well. Eg.: https://github.com/SDL-Hercules-390/hyperion/issues/181

And a screenshot from moshix includes it from a couple years ago: https://github.com/MVS-sysgen/sysgen/issues/1

So, maybe something hasn't actually be fixed yet?

[hercules.log](https://github.com/MVS-sysgen/sysgen/files/11006294/hercules.log)

**Comment by wrljet** [comment]
Greg,

`'hthread_setschedparam()' failed` is not an "error".  That's an informational warning.

It just means Hercules was not built with `setcap` permissions (which is, for example, handy if you're asking it to configure networking so you can run it without `sudo`).

If you're interested, my Hercules-Helper will build you one that won't give you that message.

Bill

**Comment by gmgauthier** [comment]
> Greg,
> 
> `'hthread_setschedparam()' failed` is not an "error". That's an informational warning.
> 
> It just means Hercules was not built with `setcap` permissions (which is, for example, handy if you're asking it to configure networking so you can run it without `sudo`).
> 
> If you're interested, my Hercules-Helper will build you one that won't give you that message.
> 
> Bill

Can you post a link?

**Comment by wrljet** [comment]
https://github.com/wrljet/hercules-helper

It supports many CPUs and OSes.  Probably yours. :)

Please read the instructions carefully first (they aren't that good, though), and don't be bashful to ask for help.
Either on the GitHub or there's a channel on the Moshix mainframe Discord for Hercules-Helper.

---

BUT, that warning msg is not causing any problems for you at this stage.

Bill

**Comment by gmgauthier** [comment]
> https://github.com/wrljet/hercules-helper
> 
> It supports many CPUs and OSes. Probably yours. :)
> 
> Please read the instructions carefully first (they aren't that good, though), and don't be bashful to ask for help. Either on the GitHub or there's a channel on the Moshix mainframe Discord for Hercules-Helper.
> 
> BUT, that warning msg is not causing any problems for you at this stage.
> 
> Bill

Well, the only thing I'd say in response to that, is that I run the latest TK4Rob in another directory, with the *same exact hercules build*, and I don't get these errors.

**Comment by wrljet** [comment]
Well, like I wrote above, it's not an ERROR.

**Comment by gmgauthier** [comment]
Sure. Whatever.

**Comment by gmgauthier** [comment]
> Well, like I wrote above, it's not an ERROR.

Okay, I finally see what you mean now. I built it with the default options (enabled capabilities) initially. So, now, my choices are: 

* Run as a user, and tolerate the messages.
* Run as root, to give Hercules the privileges it needs for thread scheduling
* Rebuild Hercules with the `--disable-capabilities` option in the configure script. 

![Screenshot from 2023-03-18 13-33-53](https://user-images.githubusercontent.com/71766306/226109497-6daa4e93-9a28-4450-b1fc-dffc04cbc983.png)
