### ISSUE TITLE
BREXX install without the example PDS

### ISSUE THREAD

**Issue by moshix** [MVS-sysgen/sysgen#4]
The brexx install of 2.4.0 (2.4.1 is out as far as I know) does not install the sys2.exec PDS with all the examples to test the brexx correct execution.

**Comment by mgrossmann** [comment]
@moshix A V2R4M1 was not officially released, yet. May be we will skip this version and will directly release a V2R5M0.

**Comment by MVS-sysgen** [comment]
I think i see the issue, i need to figure out a way to add 

```
IF &SYSDSN('BREXX.V2R4M0.RXLIB') EQ &STR(OK) THEN DO
  FREE FILE(RXLIB)
  ALLOC FILE(RXLIB) +
    DSN('BREXX.V2R4M0.RXLIB') SHR
END
```

To `SYS1.CMDPROC(TSOLOGON)`

**Comment by MVS-sysgen** [comment]
This is now fixed if you do a git pull and run `./sysgen --skip-custom` but be warned this will remove any changes you've done. If you want to manually fix it you can submit this job to the socket reader with no one logged in to fix it:

```jcl
//EDITJOB  JOB (EDIT),'EDIT',CLASS=A,MSGCLASS=A,
//                USER=IBMUSER,PASSWORD=SYS1
//EDITSTEP EXEC PGM=IKJEFT01,REGION=1024K,DYNAMNBR=50
//SYSPRINT DD  SYSOUT=*
//SYSTSPRT DD  SYSOUT=*
//SYSTERM  DD  SYSOUT=*
//SYSTSIN  DD  *
EDIT 'SYS1.CMDPROC(TSOLOGON)' DATA NONUM OLD
LIST
TOP
FIND \%STDLOGON
UP
INSERT ENDIF
INSERT IF &SYSDSN('BREXX.V2R4M0.RXLIB') EQ &STR(OK) THEN DO
INSERT  FREE FILE(RXLIB)
INSERT  ALLOC FILE(RXLIB) DSN('BREXX.V2R4M0.RXLIB') SHR
INSERT END
LIST
END SAVE
```
