### ISSUE TITLE
mvp install of PVTMACS fails

### ISSUE THREAD

**Issue by gmgauthier** [MVS-sysgen/sysgen#40]
The prerequisite installations for DSSDUMP fail due to a utf-8 error in the lookup for PVTMACS.

Console output:
```
HHC01950I Starting guest issued panel command: SH MVP/MVP  INSTALL 'PVTMACS'
HHC01603I SH MVP/MVP  INSTALL 'PVTMACS'
MVP100I - Installing PVTMACS
Traceback (most recent call last):
  File "/DATA1/Projects/foss/sysgen/MVSCE/MVP/MVP", line 416, in <module>
    mvp_user_job += infile.read().decode().strip()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd7 in position 24125: invalid continuation byte
HHC01950I Completed guest issued panel command: SH MVP/MVP  INSTALL 'PVTMACS'
/ MVP999E - ERROR - UNABLE TO FIND PVTMACS IN MTT AFTER  120 SECONDS
/ MVP999E - ERROR - INSTALL ABORTING
```
Attempting to install PVTMACS independently, failed for the same reason...

![Screenshot from 2023-03-17 22-44-41](https://user-images.githubusercontent.com/71766306/226065258-bcfefea5-b524-4f12-aaa4-436bec7b812d.png)
![Screenshot from 2023-03-17 22-49-42](https://user-images.githubusercontent.com/71766306/226065673-736f4513-7181-4bb9-8fd3-4cd895f7be71.png)

Here is a snapshot of line 24125 (in context) in the PVTMACS package (at `MVSCE/MVP/packages`):

![Screenshot from 2023-03-18 11-55-36](https://user-images.githubusercontent.com/71766306/226104536-19cd7e7c-dc8c-4e07-b055-2b7634bab922.png)

**Comment by mainframed** [comment]
Ooh nice catch, I'll track this here but in the future can you use the MVP git repo to report MVP issues? https://github.com/MVS-sysgen/MVP

**Comment by mainframed** [comment]
See https://github.com/MVS-sysgen/MVP/commit/1ce18eb175276c96a6f5ff11f51c5499a7740d3d

**Comment by gmgauthier** [comment]
> Ooh nice catch, I'll track this here but in the future can you use the MVP git repo to report MVP issues? https://github.com/MVS-sysgen/MVP

Will do!
