### ISSUE TITLE
RAKF: Panel not found

### ISSUE THREAD

**Issue by HarmBacker** [MVS-sysgen/sysgen#41]
Hello,
I had a fresh installation today (first I built Hercules from 'develop' branch, then the full installation with sysgen.py went almost well).
When using menu 'M' --> 'R' to see RAKF administration with user MVSCE01, I get 'Panel not found' message.
Regards,
Harm

**Comment by mainframed** [comment]
Those (RAKF, TSO games, Calendar) were more aspirational when i created the ISPTHEME package. I've removed them from now.
