### ISSUE TITLE
rx mvp install ind$file failes

### ISSUE THREAD

**Issue by HarmBacker** [MVS-sysgen/sysgen#47]
Hello,
I wanted to install IND$FILE but got following messages:
![image](https://user-images.githubusercontent.com/123192531/227573883-1bc60588-d879-4b22-becc-436245e1836a.png)

I did not use MVP yet as IND$FILE is the only feature I'd like to use now.
Regards,
Harm

**Comment by HarmBacker** [comment]
found the issue - user should have admin permissions. :-)

**Comment by mainframed** [comment]
This is maybe a good suggestion to check access right before running.
