### ISSUE TITLE
DSCOPY CDSCPY0 fails with UNDEFINED SYMBOLIC VARIABLE

### ISSUE THREAD

**Issue by philmpv** [MVS-sysgen/sysgen#48]
I successfully sysgen'd and RX MVP installed DSCOPY adding an option to the ISPMORE panel.  However, the CLIST CDSCPY0 fails as it doesn't recognise &SYSISPF. The error is:
IF &STR(&SYSISPF) = &STR(ACTIVE) THEN            
THIS STATEMENT HAS AN UNDEFINED SYMBOLIC VARIABLE

This function works under the Rob Prins MVS3.8 distribution so is there a PTF/FIX missing?

**Comment by philmpv** [comment]
Rob Prins distribution website http://www.prince-webdesign.nl/tk4rob lists the usermods applied.  These are the ones he applied different to your distribution: TMVS16, TMVS17,RRKF007,ZP60042,ZP60043

**Comment by philmpv** [comment]
I have been in contact with Rob Prins who confirmed the usermod ZP60038 is required.  But checking the applied usermods on sysgen this and all its perquisites have already been applied.  CLPA at IPL also doesn't fix the issue. I am now wandering if the problem may actually be with the Link Pack Area itself.

**Comment by philmpv** [comment]
I have now discovered that the &SYSISPF builtin CLIST variable is part of usermod ZP60014 rework 20201207 available on Greg Prices website https://www.prycroft6.com.au/vs2mods/#zp60014 which supercedes the ZP60014 you have in your distribution.  For a really complete install of ISPF you need the most up to date ZP60014 as well as ZP60038.

I have tried applying the up to date ZP60014 but the mysteries of SMP elude me and it rejects the update.

In an e-mail with Rob Prins he made a statement: "After a complete SYSGEN, all the usermods, which are not accepted should be re-applied." Not sure if this would sort out any of the ZP60014 updating issues but I am going to leave this well alone so as not to mess things up.  Perhaps you could update usermod ZP60014 on MVS/CE with the latest one and add a step before installing ISPF to apply/re-apply all usermods.

**Comment by mainframed** [comment]
This should be fixed in this release: https://github.com/MVS-sysgen/sysgen/releases/tag/latest please test and re-open if its not working
