### ISSUE TITLE
Hercules core dump ...

### ISSUE THREAD

**Issue by spock64** [MVS-sysgen/sysgen#49]
Hi, I installed your suggested docker package and Hercules is failing due to an illegal instruction ...

```
[*] /config/local/custom.cnf no changes
[*] Starting encrypted FTP listener on port 3221
[*] Starting encrypted TN3270 listener on port 3223
[*] Starting Hercules
./mvs.sh: line 88:    28 Illegal instruction     (core dumped) hercules -f /config/local.cnf -r conf/mvsce.rc --daemon > /logs/hercules.log
```

This is on an intel Ubuntu 23.04 box - can you share how you built your version of Hercules please? I can then have a look at why it's broken.

Thanks!

**Comment by mainframed** [comment]
Yes, not sure why, its very inconsistent (that crash)

you can checkout the docker file(s) here: https://github.com/mainframed/docker-hercules
