### ISSUE TITLE
[SOLVED]Logon hangs before presenting logon screen.

### ISSUE THREAD

**Issue by larson9999** [MVS-sysgen/sysgen#50]
I've installed MVS/CE by untarring the 202 tarball and running the start script.  When I attach the 3270 emulator it hangs when I press enter before it presents me with the logon prompt.  The working cursor spins forever.

I don't know what information I should provide but here are some things.

1. OS:ubuntu 22.04
2. Hercules: built with the latest hercules-helper script.

**Comment by mainframed** [comment]
Running the script should have created the file `hercules.log` could you please attach that to the issue?

**Comment by larson9999** [comment]
> Running the script should have created the file `hercules.log` could you please attach that to the issue?

[hercules.log](https://github.com/MVS-sysgen/sysgen/files/12110389/hercules.log)

**Comment by larson9999** [comment]
> > Running the script should have created the file `hercules.log` could you please attach that to the issue?
> 
> [hercules.log](https://github.com/MVS-sysgen/sysgen/files/12110389/hercules.log)

That log file was created using the first installation I tried. When I try to run it now there is no log file created.

**Comment by larson9999** [comment]
> Running the script should have created the file `hercules.log` could you please attach that to the issue?

[Uploading hercules.log…]()

**Comment by larson9999** [comment]
I wonder if I'm missing a step.  I've tried this again on a new machine and get similar results.  Here's what I'm doing.
1. Download and untar the tarball .
2. Install hercules via the hercules-helper script.
3.cd to the MVSCE directory.
4. run start_mvs.sh from the MVSCE tarball.
5. Connect x3270 to the running mvs.
6. Hit enter.  This is where it hangs and doesn't let me log in.

**Comment by larson9999** [comment]
finally got this working by installing another version of hercules via hercules-helper

~/hercules-helper/hercules-buildall.sh --auto --flavor=aethra

**Comment by larson9999** [comment]
This was solved for me by installing the Jay Mosley version via Hercules Helper.
