### ISSUE TITLE
SYS1.UMODMAC and SYS2.MACLIB - problems with custom network solicitors

### ISSUE THREAD

**Issue by roblthegreat** [MVS-sysgen/sysgen#9]
I'm not sure if this is an ANSi2EBCDiC or MVS-sysgen issue but generating a simple network solicitor using ansi2ebcdic --sysgen and then submitting the result will have 2 issues.  

1. The ansi2ebcdic generated JCL job includes a DD for `SYS2.MACLIB` which doesn't exist on a fresh sysgen.  

2. After removing the SYS2.MACLIB reference, it assembles and runs without issue (CC=0). However after restarting VTAM, the 3270 data-stream of the resulting network solicitor is all jumbled together.  A little troubleshooting points to the fact `SYS1.UMODMAC `is missing the  3270 stream macros - `$WCC, $SBA, $SF, $IC,` etc.   The macros are included in TK4-, but don't appear in MVS-sysgen.

Is it expected to include those macros in MVS-sysgen, or should an `ansi2ebcdic --sysgen` be adding the raw DC instruction equivalents?  I noted that the default network solicitor included with MVS-sysgen isn't using the 3270 data stream macros, but raw DC.

Also, should the `SYS2.MACLIB` exist by default? 

## Attachments
* [TEST-NETSOL.ans.gz](https://github.com/MVS-sysgen/sysgen/files/6682360/TEST-NETSOL.ans.gz) (gzipped as github wouldn't allow *.ans files directly) - Moebius file
* [TEST-NETSOL.txt](https://github.com/MVS-sysgen/sysgen/files/6682355/TEST-NETSOL.txt) - Output from ansi2ebcdic

## Steps to reproduce:
1. Cloned MVS-sysgen as of June 19th 2021.
2. Ran `sysgen.sh` without any arguments (default sysgen) and then IPLed.
3. Using latest "Moebius", created a `test-netsol.ans` (attached)
![Moebius Screenshot](https://user-images.githubusercontent.com/354025/122675036-486b6300-d19d-11eb-969e-07f0cbbb45ce.PNG)
4. Cloned ansi2ebcidic as of June 19th 2021.
5. Executed ansi2ebcdic with `--jobname HMVS01A --ROW 23 --COL 13 --sysgen`
6. Deleted the lines of TEST-NETSOL.txt before the start of the job card (lines 1 to 26)
7. Submitted and it will fail due to missing `SYS2.MACLIB`
8. Deleted the reference to `SYS2.MACLIB` (Line 174) in TEST-NETSOL.txt
9. Submitted again.  Completes with CC=0.
10. Restarted VTAM
11. Connected with TN3270 and the newly generated network solicitor appears.  No line breaks, but everything seems to just run together. 
![TN3270 Screenshot](https://user-images.githubusercontent.com/354025/122675423-faeff580-d19e-11eb-8871-a112187c4ef0.PNG)

**Comment by mainframed** [comment]
The SYSGEN output uses some macros from SYS2.MACLIB but its not installed by default. Use `INSTALL EXTRAS` to install them (I've just renamed the software to `MACLIBS` so there's less confusion in the future and you;'ll be able to use `INSTALL MACLIBS`)

**Comment by mainframed** [comment]
Sorry didn't mean to close the issue. Let me know if this fixes your problem so I can close it.
